FROM node:22.14.0-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production && \
    npm cache clean --force
COPY src ./src
COPY bin ./bin

FROM node:22.14.0-alpine
WORKDIR /app

ARG DB_CONNECTION
ARG JWT_SECRET
ARG JWT_EXPIRES
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG FACEBOOK_APP_ID
ARG FACEBOOK_APP_SECRET

ARG AGENDA_URL
ARG BIBLIOTECAS_URL
ARG CENTROS_TIEMPO_LIBRE_URL
ARG GALERIAS_ARTE_URL
ARG MUSEOS_URL
ARG SALAS_EXPOSICIONES_URL
ARG SALAS_MUSICA_URL
ARG TEATROS_URL
ARG ZONAS_JOVEN_URL

ENV DB_CONNECTION=$DB_CONNECTION \
    JWT_SECRET=$JWT_SECRET \
    JWT_EXPIRES=$JWT_EXPIRES \
    GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID \
    GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET \
    FACEBOOK_APP_ID=$FACEBOOK_APP_ID \
    FACEBOOK_APP_SECRET=$FACEBOOK_APP_SECRET

ENV AGENDA_URL=$AGENDA_URL \
    BIBLIOTECAS_URL=$BIBLIOTECAS_URL \
    CENTROS_TIEMPO_LIBRE_URL=$CENTROS_TIEMPO_LIBRE_URL \
    GALERIAS_ARTE_URL=$GALERIAS_ARTE_URL \
    MUSEOS_URL=$MUSEOS_URL \
    SALAS_EXPOSICIONES_URL=$SALAS_EXPOSICIONES_URL \
    SALAS_MUSICA_URL=$SALAS_MUSICA_URL \
    TEATROS_URL=$TEATROS_URL \
    ZONAS_JOVEN_URL=$ZONAS_JOVEN_URL

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/src ./src
COPY --from=builder /app/bin ./bin
COPY package*.json ./

RUN addgroup -S appgroup && \
    adduser -S appuser -G appgroup && \
    chown -R appuser:appgroup /app

USER appuser
EXPOSE 3000

CMD ["node", "./bin/www"]